* Презентация к дипломной работе

  [[https://docs.google.com/presentation/d/1yvQZNiBJ27dwnHgTJZ6JOn9aQXyNqLXSRXa7gYDbZcI/edit?usp=sharing][Google slides]]

** Метаинформация:
   - время 5-6 минут
   - рекомендуемая структура:
     + титульный слайд
     + решаемая проблема
       * предметная область
       * актуальность
       * цели и задачи исследования
     + постановка задачи
       * ясная и четкая
     + Решение задачи (несколько слайдов)
     + Апробация 
       * в том числе, сравнение с существующими решениями
     + Полученные результаты

** План презентации

*** Титульник 
*** Введение: системы интерактивных доказательств
    Сейчас актуальна тема формальных верификаций. 
    Особенно в областях медицины, финансов или построения компиляторов.
      
    Системы интерактивных доказательств, к которым относится например coq, agda и hol, позволяют
    формализовать и написать доказательство выполнения свойств сложной системы, и берут на
    себя проверку этих доказательств.

*** Введение: модели памяти
    Одной из таких сложных систем является модель памяти языка программирования, которая специфицирует
    поведение параллельных программ.
    
    Один из подходов к построения моделей памяти, аксиоматический, заключается в
    анализе бинарных отношений над событиями записи/чтения, которые строятся по всевозможным исполнениям программы.
    
    После чего *на полученный граф* накладывается ограничения, 
    которые запрещают некоторые поведения.
    
    Модели памяти все чаще сейчас переносятся в систему Coq, так как они требуют объемных
    и технически сложных доказательств. 

    Coq позволяет переложить на компьютер проверку этих доказательств и также частично их
    автоматизировать.  

    О чем далее и пойдет речь.

*** Введение: Алгебра Клини 
    Алгебра Клини - это аксиоматическая формальная система, состоящая из операций объединения,
    последовательной композиции, замыкания Клини, пустого отношения и множества всех петель.

    Выводимость неравенств в этой теории влечет за собой верность
    вложенности бинарных отношений, если эта вложенность сохраняется для любых значений переменных.

    Для такой теории можно реализовать *алгоритм вывода неравенств* в Coq, что
    позволит автоматически доказывать вложенность бинарных отношений.
    
*** Цель работы
    Исследовать возможность применения теории алгебр Клини для упрощения доказательств в системе Coq,
    которые связаны с моделями памяти.

*** Клини алгебра с тестами
**** слайд 1 
     Интересным расширением алгебр Клини являются теория алгебры Клини с тестами, которая добавляет к
     бинарным отношениям предикаты на домены. Операция квадратные скобки отражает предикат в
     петли над элементами, для которых он истинен.

     Это делает более широким класс утверждений, которые мы можем автоматически доказывать.

     Это позволяет например выразить факт, что отношение "чтение из" задано только между операциями
     чтения и записи с помощью таких маркерных предикатов. 

     /То есть если последовательно соединить петли
     над оп ерациями записи отношние rf и петлями над операциями чтения то отношение по сути фильтруя
     его, отношение не изменится./

**** слайд 2
     Также эта теория поддерживает вывод неравенств из гипотез специального вида, что позволяет
     автоматизировать доказательства не только общезначимые свойства.
    
     И это единственное на данный момент расширение теории Клини, для которого существует полная
     реализация в Coq. А именно в бибилотеке relation-algebra.

*** Hahn
    В моей работе предлагается применить этот метод автоматизации свойств *бинарных отношений с тестами* к библиотеке hahn.
    
    *Hahn содержит определения и доказательство свойств базовый формализма* моделей памяти, в том числе
    для бинарных отношений. 
    Hahn используется во многих важных проектах в области моделей памяти,
    что позволит оценить применимость этого подхода и
    расширить набор предоставляемых hahn инструментов для доказательств.

*** Задачи работы
    - Интегриовать средства автоматического вывода общезначимых  неравенств в hahn
    - Упростить доказательства в hahn
    - Оценить упрощение доказательств

*** Решение
    - Для этого была сопоставлена сигнатура KAT и определения операций с бинарными отношениями в hahn
    - Доказано выполнение аксиом KAT для этих определений, **что позволило использовать автоматизацию из
      библиотеки relation-algebra.**
    - По возможности были переформулированы определения в hahn через сигнатуру KAT, чтобы появилась
      возможность их также автоматизировать

*** Пример переформулирования (max_elt)
**** слайд 1    
     Для примера рассмотрим определение свойства элемента =a= быть максимальным в отношении =r=.
     В hahn оно выглядело так: 
     для любого элемента =b= не выполняется =r a b=, 
     то есть не существует ребер исходящих из =a=, максимльного элемента. 

     Мы можем переформулировать это утверждение в KAT: предикат равенства с =a= последовательно
     скомпозированный с r дает не более чем пустое множество. То есть нет путей, которые проходят по
     петле в элементе =a= и потом проходят по отношению =r=. 

     Новое определение эквивалентно предыдущему...
 
**** слайд 2
***** Лемма о переформулировании
      ... мы сформулируем это в виде леммы об эквивалетности =max_elt_iff_kat= и докажем ее в Coq. 
      Лемма выражает то, 
      что для любый =a= и =r= из одного определения следует другое, и наоборот.

      А теперь посмотрим как это позволяет упрощать доказательства.

***** Маскимальный элемент транзитивного замыкания
      В hahn есть лемма о том, что максимальный элемент отношения r является максимальным элементом и
      для его транзитивного замыкания.
      
***** Старое доказательство
      Так выглядело старое доказательство: оно несложное, но требует некоторое количество действий.
      Упростим его.

***** Переписывание
      В первой строчке доказательства (6 строчка на слайде) мы с помощью леммы об эквивалетности
       можем заменить старые определения на новые в утверждении леммы.

      В результате, мы получим утверждений которое содержит только элементы сигнату KAT. 

***** Завершаем
      Так как гипотеза, слева от стрелки претвлена в виде "что-то" меньше нуля, то команда hkat из
      библиотеки relation-algebra может автоматически завершить доказательство.

***** Как в итоге выглядит решение
      Для удобства мы можем собрать все операции по переформулированию вместе и обьединить с hkat в
      одну команду hahn_hkat. В итоге, наше доказательство упростилось до одной команды.
      
      Новый инструмент позволяет, не изменяя внешней сигнатуры лемм,
      частично или полностью автоматизировать их доказательства.

*** Статистика
    Оценим как много доказательств получилось упростить подобным образом.

    В общей сложности в hahn получилось упростить примерно треть лемм, связанных с бинарными
    отношениями. Большая часть из них автоматизировались полностью. 
    Также треть объема доказательств удалось заменить новыми командами, что сократило общий размер
    доказательств на 16 процентов.

    Остальные доказательства упростить не удалось потому что их нельзя выразить в сигнатуре KAT или они
    следуют из гипотез, которые эта теория не поддерживает.

    Размер кода составил 315 строчек, а размер доказательств в hahn строго уменьшился 

*** Результаты работы
    - В Hahn добавлены новый инструмент для автоматизации доказательств общезначимых и следующих их
      специальных гипотез неравенств.
    - Он был опробован на доказательствах в самом hahn в результате чего получилось
      упростить существенное количество лемм.

   Из чего можно сделать вывод, что теория алгебр Клини действительно может упростить работу с моделей
   памяти в системе Coq.

*** Запасные слайды:
    - Таблица всех переформулирований
    - Переформулирования вне KAT
    - Выды гипотез, которые можно использовать
    - Пример общезначимых неравенств
    - Пример доказательства из гипотез
    - Пример всех исполенений программы

