* Презентация к дипломной работе

  [[https://docs.google.com/presentation/d/1c9itHz_mKdMtt-jsgyNcBAzFgRIWwGmYwoPhsS744cY/edit?usp=sharing][Ссылка на google slides]]
   
   

** Метаинформация:
   - время 5-6 минут
   - рекомендуемая структура:
     + титульный слайд
     + решаемая проблема
       * предметная область
       * актуальность
       * цели и задачи исследования
     + постановка задачи
       * ясная и четкая
     + Решение задачи (несколько слайдов)
     + Апробация 
       * в том числе, сравнение с существующими решениями
     + Полученные результаты

** План презентации DRAFT

*** [слайд 1] Титульник
    - Найти шаблон
    - Название
    - Вспомнить свое имя, имя консультанта и руководителя
*** [слайд 2] Актуальность
    Рассказать про модели памяти и корректность

    Картинки у Виктора.
*** [слайд 3] Предметная область
    Рассказать Про KA, KAT, KAC, KL (нужное подчеркнуть).
    
    Подергать картинки из дисера.
*** [слайд 4] Цели и задачи исследования
    Исследовать применение алгебры Клини и ее расширений для автоматизации доказательств.
    Применение ее к моделям памяти.
    
*** [слайд 5] Постановка задачи
    Оценить какое количество доказательств возможно сократить используя существующие реализации алгебр Клини в Coq.
*** [слайд 6] ATBR и relation-algebra.
    Рассказать, что в них есть и почему это полезно
*** [слайд 7] Реализация инстансов
    Рассказать как использовать relation-algebra
    Что мы для этого сделали.
    Вставить пару примеров.
*** [слайд 8] Рассказать про проблемы в реализации
    - Проблема инстацирования
    - Проблема перформанса
*** [слайд 9] Апробация 
    Рассказать, что в итоге получилось. Статистика.
    Рассуждения про то, что эвристики - это плохо, а теория Клини - хорошо.
*** [слайд 10] Итоги
    Сказать, что в целом у этого подхода есть большой потенциал, которые сокращает жизнь исследователям моделей памяти.
    
    ?? Может рассказать, что хотелось бы сделать в дальнейшем.
    - Исследовать вопрос  проверки на пустоту пересечения нескольких отношений.
