
:overview:
Первая версия пояснительно записки (thesis) (черновой вариант)
Тема: Применение теории Алгебр Клини и ее расширений для автоматизации доказательств в системе Coq.

TODO Подумать, как писать прямо в org-mode
:end:

#+TITLE: Выпускная квалификационная работа (Бакалавриат)
#+TITLE: Тема: Применение теории алгерб Клини и ее расширений для автоматизации доказательст в системе Coq.
#+AUTHOR: Головин Павел, КТ M3439

* Оглавление
  *Тут должны быть автогенерация*
* Введение
  :Needs:
  - [ ] Актуальность работы
  - [ ] Цели и задачи работы
  - [ ] Новизна работы
  - [ ] Практическое значение работы
  - [ ] Ссылки на доклады и публикации
  - [ ] Краткое описание структуры работы по главам
  :end:

  В информатике часто используется такая математическая абстракция как бинарные отношения.
  Она позволяет выразить некоторое характерное свойство пары объектов. Например, отношения порядка, отношения эквивалентности, функциональные отношения, отношения инцендентности вершин в графе и т.д.
  Так же часто бинарные отнощения необходимы для анализа свойства исполнения параллельных программ. Модели памяти языка программирования используют отношения порядка исполенения команд, отношение "произошло до" и другие отношения на элементарых операциях, чтобы специфицировать поведение программы при наличии гонок по данным.
  
  Теоритически формальные модели памяти могут просто запрещать наличие гонок в коде как это было в языке Си до введения модели памяти C11 (link?). Это сильно ограничивает производительность и параллелизм программ. Поэтому сейчас языки по возможности используют в своей спецификации так называемые слабые модели памяти, которые разрешают гонки по данным и специфицируют набор возможных поведений программы. Но проблема в том, создание формальной слабой модели памяти, которая корректная применима при компиляции программы по разные архитектуры - это очень сложная задача. Так как например слабые модели C11 и JMM имеют проблему значений из воздуха (link?). 

  Поэтому при разработке новых модели памяти RC11 (link?) стараются использовать системы для автоматической проверки доказательств, таких как язык с зависимыми типами Coq. 
  Такой подход включает в себя аксиомотизацию модели памяти и модели исполнения, а также доказательство теорем о корректности компиляции на языке Coq. Это позволяет быть уверенным в правильности сложной модели памяти.

  В процессе формализации модели памяти на языке Coq приходится доказывать большое количество лемм и свойств исходя из базовых аксиом. Средства Coq также позволяют автоматизировать и переиспользовать доказательства, путем обобщения доказываемых утверждений. 

  Так как работая с моделью памяти мы часто имеем дело с бинарными отношениями, то можно попробовать обобщить и вынести доказательства утвержений связанные с бинарными отношениями в отдельные модули и переиспользовать их. Алгебраическим обобщением бинарных отношения явлюяется Алгебра Клини (линк?).

  Цель данной работы заключается в попытке упростить формальные доказательства в системе Coq связанные с моделями памяти, путем автоматизации доказательств утвержений об объектах алебры Клини и ее расширений. Это возволит упростить разработку слабых моделей памяти в системе Coq.

** Описание глав
   TODO
 
* Главы

** Глава 1

*** Описание предметной области
**** Алгеба отношений
     Для любого множетсва O, можно задать алгебру отношений Rel<O> \sube \Rho(O) с операциями:
     - композиции (\cdot) и нейтральным элементом
     - рефлексивного тразитивного замыкания (_^*)
    Также дополнительно мы определим операции:
     - тразитивного замыкания (^{+})
     - пересечения(\cap) и объединения(\cup) 
     - инвертирования (^\cup) (x R y \Leftrightarrow y R^\cup x)
    и пустое (0) и универсальное множество T
**** Алгебра Клини
     (линк на Algebra of Relation)
     Назовем алгеброй клини и будем обозначать как KA кортеж <A, +, \cdot, _^*, 0, 1> такой, что <A, +, \cdot, 0, 1> - идемпотентное полу-кольцо и операция _^* удовлетворяет ряду аксиом (TODO)
     Известно, что Алгебра Клини полна относительно алгебры отношений (link).
**** Алгебра Клини с тестами
     Теперь рассмотрим очень полезное расширение KA, алгебры Клини с тестами.
     Клини алгебра с тестами (KAT), это кортеж <K, B, [\cdot]> такой, что:
     - K - Клини алгебра (K=<A, +, \cdot, _^*, 0, 1>)
     - B - булева алгебра (B=<B, \wedge, \vee, T, \bot>)
     - [\cdot] - гоморфизм из <A, +, \cdot, _^*, 0, 1> в <B, \wedge, \vee, T, \bot>
     
     Чтобы сохранить полноту с бинарными отношениями расширим определение бинарных отношений, добавив к нему булеву алгебру \Rho(O) с естественной теоретико-множественной интерпретацией всех связок. А гоморфизм определим следующим образом [a] = {(p, p) \in a}.
     Алгебра Клини с тестами полна относительно такой расширенной алгебры бинарных отношений. (link)
     Элементы булевой алгебры называют тестами. Они позволяют нам ограничивать наши бинарные отношения какими-то логическими выражениями.

**** relation-algebra
     
     
**** Hahn

*** Анализ

    

*** Постановка задачи

    

*** выводы

** Глава 2

*** Предполагаемое теоритическое решение (подход/метод/алгоритм/схема)

*** Обоснование, почему оно удовлетворяет тербованиям, сформулированным в первой главе.

*** Теоретическое сравнение с существующими решенями

** Глава 3

* Заключение
* Список источников
* Приложения
